# coding: utf-8

"""
    YTB-CRAWLER

    YTB-CRAWLER

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ChannelLog(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'code': 'str',
        'value': 'str',
        'id': 'float',
        'channel_id': 'float',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'channel_pll_id': 'float'
    }

    attribute_map = {
        'type': 'type',
        'code': 'code',
        'value': 'value',
        'id': 'id',
        'channel_id': 'channelId',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt',
        'channel_pll_id': 'channelPllId'
    }

    def __init__(self, type=None, code=None, value=None, id=None, channel_id=None, created_at=None, updated_at=None, channel_pll_id=None):
        """
        ChannelLog - a model defined in Swagger
        """

        self._type = None
        self._code = None
        self._value = None
        self._id = None
        self._channel_id = None
        self._created_at = None
        self._updated_at = None
        self._channel_pll_id = None

        if type is not None:
          self.type = type
        if code is not None:
          self.code = code
        if value is not None:
          self.value = value
        if id is not None:
          self.id = id
        if channel_id is not None:
          self.channel_id = channel_id
        if created_at is not None:
          self.created_at = created_at
        if updated_at is not None:
          self.updated_at = updated_at
        if channel_pll_id is not None:
          self.channel_pll_id = channel_pll_id

    @property
    def type(self):
        """
        Gets the type of this ChannelLog.

        :return: The type of this ChannelLog.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ChannelLog.

        :param type: The type of this ChannelLog.
        :type: str
        """

        self._type = type

    @property
    def code(self):
        """
        Gets the code of this ChannelLog.

        :return: The code of this ChannelLog.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this ChannelLog.

        :param code: The code of this ChannelLog.
        :type: str
        """

        self._code = code

    @property
    def value(self):
        """
        Gets the value of this ChannelLog.

        :return: The value of this ChannelLog.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this ChannelLog.

        :param value: The value of this ChannelLog.
        :type: str
        """

        self._value = value

    @property
    def id(self):
        """
        Gets the id of this ChannelLog.

        :return: The id of this ChannelLog.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ChannelLog.

        :param id: The id of this ChannelLog.
        :type: float
        """

        self._id = id

    @property
    def channel_id(self):
        """
        Gets the channel_id of this ChannelLog.

        :return: The channel_id of this ChannelLog.
        :rtype: float
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """
        Sets the channel_id of this ChannelLog.

        :param channel_id: The channel_id of this ChannelLog.
        :type: float
        """

        self._channel_id = channel_id

    @property
    def created_at(self):
        """
        Gets the created_at of this ChannelLog.

        :return: The created_at of this ChannelLog.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this ChannelLog.

        :param created_at: The created_at of this ChannelLog.
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """
        Gets the updated_at of this ChannelLog.

        :return: The updated_at of this ChannelLog.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """
        Sets the updated_at of this ChannelLog.

        :param updated_at: The updated_at of this ChannelLog.
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def channel_pll_id(self):
        """
        Gets the channel_pll_id of this ChannelLog.

        :return: The channel_pll_id of this ChannelLog.
        :rtype: float
        """
        return self._channel_pll_id

    @channel_pll_id.setter
    def channel_pll_id(self, channel_pll_id):
        """
        Sets the channel_pll_id of this ChannelLog.

        :param channel_pll_id: The channel_pll_id of this ChannelLog.
        :type: float
        """

        self._channel_pll_id = channel_pll_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ChannelLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
