# coding: utf-8

"""
    YTB-CRAWLER

    YTB-CRAWLER

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Country(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'code': 'str',
        'meta_data': 'object',
        'id': 'float',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'topic_id': 'float'
    }

    attribute_map = {
        'name': 'name',
        'code': 'code',
        'meta_data': 'metaData',
        'id': 'id',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt',
        'topic_id': 'topicId'
    }

    def __init__(self, name=None, code=None, meta_data=None, id=None, created_at=None, updated_at=None, topic_id=None):
        """
        Country - a model defined in Swagger
        """

        self._name = None
        self._code = None
        self._meta_data = None
        self._id = None
        self._created_at = None
        self._updated_at = None
        self._topic_id = None

        if name is not None:
          self.name = name
        if code is not None:
          self.code = code
        if meta_data is not None:
          self.meta_data = meta_data
        if id is not None:
          self.id = id
        if created_at is not None:
          self.created_at = created_at
        if updated_at is not None:
          self.updated_at = updated_at
        if topic_id is not None:
          self.topic_id = topic_id

    @property
    def name(self):
        """
        Gets the name of this Country.

        :return: The name of this Country.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Country.

        :param name: The name of this Country.
        :type: str
        """

        self._name = name

    @property
    def code(self):
        """
        Gets the code of this Country.

        :return: The code of this Country.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this Country.

        :param code: The code of this Country.
        :type: str
        """

        self._code = code

    @property
    def meta_data(self):
        """
        Gets the meta_data of this Country.

        :return: The meta_data of this Country.
        :rtype: object
        """
        return self._meta_data

    @meta_data.setter
    def meta_data(self, meta_data):
        """
        Sets the meta_data of this Country.

        :param meta_data: The meta_data of this Country.
        :type: object
        """

        self._meta_data = meta_data

    @property
    def id(self):
        """
        Gets the id of this Country.

        :return: The id of this Country.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Country.

        :param id: The id of this Country.
        :type: float
        """

        self._id = id

    @property
    def created_at(self):
        """
        Gets the created_at of this Country.

        :return: The created_at of this Country.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this Country.

        :param created_at: The created_at of this Country.
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """
        Gets the updated_at of this Country.

        :return: The updated_at of this Country.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """
        Sets the updated_at of this Country.

        :param updated_at: The updated_at of this Country.
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def topic_id(self):
        """
        Gets the topic_id of this Country.

        :return: The topic_id of this Country.
        :rtype: float
        """
        return self._topic_id

    @topic_id.setter
    def topic_id(self, topic_id):
        """
        Sets the topic_id of this Country.

        :param topic_id: The topic_id of this Country.
        :type: float
        """

        self._topic_id = topic_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Country):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
