# coding: utf-8

"""
    YTB-CRAWLER

    YTB-CRAWLER

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Lyric(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'language': 'str',
        'text': 'str',
        'id': 'float',
        'audio_clean_id': 'float',
        'created_at': 'datetime',
        'updated_at': 'datetime'
    }

    attribute_map = {
        'language': 'language',
        'text': 'text',
        'id': 'id',
        'audio_clean_id': 'audioCleanId',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt'
    }

    def __init__(self, language=None, text=None, id=None, audio_clean_id=None, created_at=None, updated_at=None):
        """
        Lyric - a model defined in Swagger
        """

        self._language = None
        self._text = None
        self._id = None
        self._audio_clean_id = None
        self._created_at = None
        self._updated_at = None

        if language is not None:
          self.language = language
        if text is not None:
          self.text = text
        if id is not None:
          self.id = id
        if audio_clean_id is not None:
          self.audio_clean_id = audio_clean_id
        if created_at is not None:
          self.created_at = created_at
        if updated_at is not None:
          self.updated_at = updated_at

    @property
    def language(self):
        """
        Gets the language of this Lyric.

        :return: The language of this Lyric.
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """
        Sets the language of this Lyric.

        :param language: The language of this Lyric.
        :type: str
        """

        self._language = language

    @property
    def text(self):
        """
        Gets the text of this Lyric.

        :return: The text of this Lyric.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """
        Sets the text of this Lyric.

        :param text: The text of this Lyric.
        :type: str
        """

        self._text = text

    @property
    def id(self):
        """
        Gets the id of this Lyric.

        :return: The id of this Lyric.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Lyric.

        :param id: The id of this Lyric.
        :type: float
        """

        self._id = id

    @property
    def audio_clean_id(self):
        """
        Gets the audio_clean_id of this Lyric.

        :return: The audio_clean_id of this Lyric.
        :rtype: float
        """
        return self._audio_clean_id

    @audio_clean_id.setter
    def audio_clean_id(self, audio_clean_id):
        """
        Sets the audio_clean_id of this Lyric.

        :param audio_clean_id: The audio_clean_id of this Lyric.
        :type: float
        """

        self._audio_clean_id = audio_clean_id

    @property
    def created_at(self):
        """
        Gets the created_at of this Lyric.

        :return: The created_at of this Lyric.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this Lyric.

        :param created_at: The created_at of this Lyric.
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """
        Gets the updated_at of this Lyric.

        :return: The updated_at of this Lyric.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """
        Sets the updated_at of this Lyric.

        :param updated_at: The updated_at of this Lyric.
        :type: datetime
        """

        self._updated_at = updated_at

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Lyric):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
