# coding: utf-8

"""
    YTB-CRAWLER

    YTB-CRAWLER

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RatingFontFamily(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'account_id': 'float',
        'font_family_id': 'float'
    }

    attribute_map = {
        'id': 'id',
        'account_id': 'accountId',
        'font_family_id': 'fontFamilyId'
    }

    def __init__(self, id=None, account_id=None, font_family_id=None):
        """
        RatingFontFamily - a model defined in Swagger
        """

        self._id = None
        self._account_id = None
        self._font_family_id = None

        if id is not None:
          self.id = id
        if account_id is not None:
          self.account_id = account_id
        if font_family_id is not None:
          self.font_family_id = font_family_id

    @property
    def id(self):
        """
        Gets the id of this RatingFontFamily.

        :return: The id of this RatingFontFamily.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this RatingFontFamily.

        :param id: The id of this RatingFontFamily.
        :type: float
        """

        self._id = id

    @property
    def account_id(self):
        """
        Gets the account_id of this RatingFontFamily.

        :return: The account_id of this RatingFontFamily.
        :rtype: float
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """
        Sets the account_id of this RatingFontFamily.

        :param account_id: The account_id of this RatingFontFamily.
        :type: float
        """

        self._account_id = account_id

    @property
    def font_family_id(self):
        """
        Gets the font_family_id of this RatingFontFamily.

        :return: The font_family_id of this RatingFontFamily.
        :rtype: float
        """
        return self._font_family_id

    @font_family_id.setter
    def font_family_id(self, font_family_id):
        """
        Sets the font_family_id of this RatingFontFamily.

        :param font_family_id: The font_family_id of this RatingFontFamily.
        :type: float
        """

        self._font_family_id = font_family_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RatingFontFamily):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
