from __future__ import absolute_import

# import apis into api package
from .account_api import AccountApi
from .account_token_api import AccountTokenApi
from .add_video_to_playlist_api import AddVideoToPlaylistApi
from .album_spotify_api import AlbumSpotifyApi
from .analytic_api import AnalyticApi
from .audio_clean_api import AudioCleanApi
from .audio_template_video_api import AudioTemplateVideoApi
from .author_api import AuthorApi
from .category_api import CategoryApi
from .channel_api import ChannelApi
from .channel_category_api import ChannelCategoryApi
from .channel_country_api import ChannelCountryApi
from .channel_image_api import ChannelImageApi
from .channel_log_api import ChannelLogApi
from .channel_need_sub_api import ChannelNeedSubApi
from .channel_pll_api import ChannelPllApi
from .channel_server_api import ChannelServerApi
from .channel_singer_api import ChannelSingerApi
from .channel_sub_api import ChannelSubApi
from .comment_api import CommentApi
from .container_api import ContainerApi
from .country_api import CountryApi
from .discussion_api import DiscussionApi
from .font_family_api import FontFamilyApi
from .image_clean_api import ImageCleanApi
from .keyword_api import KeywordApi
from .language_api import LanguageApi
from .live_api import LiveApi
from .lyric_api import LyricApi
from .music_genre_api import MusicGenreApi
from .musical_market_api import MusicalMarketApi
from .notification_api import NotificationApi
from .playlist_api import PlaylistApi
from .playlist_template_api import PlaylistTemplateApi
from .rating_audio_api import RatingAudioApi
from .rating_font_family_api import RatingFontFamilyApi
from .rating_image_api import RatingImageApi
from .raw_audio_api import RawAudioApi
from .raw_image_api import RawImageApi
from .recognition_api import RecognitionApi
from .server_api import ServerApi
from .server_log_api import ServerLogApi
from .singer_api import SingerApi
from .stream_key_api import StreamKeyApi
from .sub_category_api import SubCategoryApi
from .task_sub_channel_api import TaskSubChannelApi
from .template_video_api import TemplateVideoApi
from .title_api import TitleApi
from .topic_api import TopicApi
from .version_api import VersionApi
from .version_sever_api import VersionSeverApi
from .video_api import VideoApi
from .video_check_license_api import VideoCheckLicenseApi
from .video_list_api import VideoListApi
from .video_live_stream_api import VideoLiveStreamApi
from .video_render_api import VideoRenderApi
from .view_api import ViewApi
